[#instructlab]
== ¡Bienvenido al workshop!

La IA está cambiando por completo nuestra forma de trabajar: nos ayuda a obtener información, predecir resultados, crear contenido... Cuando hablamos de IA generativa de texto, hablamos de LLMs (Modelos de Lenguaje Grandes). Sin meternos en lo técnico, los LLMs son redes de neuronas. Reciben un input (lo que llamamos prompt), lo procesan con un algoritmo y devuelven un output, esa respuesta que parece una conversación. 

Probablemente ya hayas interactuado con un LLM. ChatGPT, Google Gemini o GitHub Copilot usan LLMs propios, de tamaños gigantescos, que requieren de muchísima potencia computacional para entrenar. ¿Y si creamos nuestro propio LLM? De esta forma podremos interactuar con él sin conexión a internet, con la privacidad de nuestros servidores y datos privados.

Puede parecer una tarea complicada, ¡pero ahí entra en juego InstructLab! Se trata de una plataforma open-source que nos permite entrenar fácilmente a estos modelos de lenguaje. Además de que nos permite descargar y servir modelos, chatear con ellos, etc...

[#objetivos]

== 🏁 Objetivos del Laboratorio 1: InstructLab y la IA generativa

En este laboratorio, trabajaremos para una compañía de seguros ficticia, Parasol. Esta empresa quiere utilizar modelos de IA generativa para responder preguntas sobre accidentes de vehículos y así acelerar el ritmo de trabajo de sus equipos.

En resumen, lo que haremos será:

1. *Interactuar con un modelo base*. Configuraremos InstructLab e interactuaremos mediante un chat.
2. *Preparar el entrenamiento*. Descubrirás la pieza central de InstructLab, las taxonomías.
3. *Comprobar el resultado final*. Chatearemos con el modelo entrenado para ver los resultados.

Te guiaremos paso a paso a lo largo del laboratorio. Recuerda que InstructLab es una herramienta que no requiere de conocimientos previos en el ámbito de la inteligencia articial.

== 🏁 Objetivos del Laboratorio 2: Agentes

Ollama
LLamaStack
Ramalama

Modelos LLama